import { DataProvider } from "./DataContext";
import SessionProvider from "./providers/sessionProviders";
import "./globals.css";
export const metadata = {
  title: "Tripma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <DataProvider>{children}</DataProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
