export const flights = [
  {
    id: 1,
    img: "flight_image/Hawaiian Airlines.svg",
    flight_number: "FIG4312",
    airline_name: "Hawaiian Airlines",
    duration: "16h 45m",
    from: "SFO",
    to: "ATL",
    oneWayDate: "Dec 30",
    dateRange: "Jan 04 - Jan 07",
    departure_time: "7:00 AM",
    return_time: "4:15 PM",
    stop_number: "1",
    stop_duration: "2h 45m",
    stop_place: "HNL",
    round_trip_price: "503",
    available_seats: 20,
    seat_class: "a",
    city: "California",
    country: "US",
    to_city: "Tokyo",
    to_country: "Japan",
    trip_seat: "Business",
  },
  {
    id: 2,
    img: "flight_image/japan Airlines.svg",
    flight_number: "FIG4987",
    airline_name: "Japan Airlines",
    duration: "19h 45m",
    from: "SFO",
    to: "ATL",
    oneWayDate: "Dec 30",
    dateRange: "Jan 04 - Jan 07",
    departure_time: "7:00 AM",
    return_time: "4:15 PM",
    stop_number: "1",
    stop_duration: "2h 45m",
    stop_place: "NPT",
    round_trip_price: "650",
    available_seats: 20,
    seat_class: "a",
    city: "California",
    country: "US",
    to_city: "Tokyo",
    to_country: "Japan",
    trip_seat: "Economy",
  },
  {
    id: 3,
    img: "flight_image/japan Airlines.svg",
    flight_number: "FIG4312",
    airline_name: "Hawaiian Airlines",
    duration: "16h 45m",
    from: "ATL",
    to: "LAX",
    oneWayDate: "Dec 30",
    dateRange: "Dec 26 - Dec 30",
    departure_time: "7:00AM",
    return_time: "4:15PM",
    stop_number: "1",
    stop_duration: "2h 45m",
    stop_place: "HNL",
    round_trip_price: "663",
    seat_class: "a",
    available_seats: 50,
    from_city: "Tokyo",
    from_country: "Japan",
    to_city: "California",
    to_country: "US",
    trip_seat: "business",
  },
  {
    id: 4,
    img: "flight_image/Hawaiian Airlines.svg",
    flight_number: "FIG4312",
    airline_name: "Japan Airlines",
    duration: "16h 45m",
    from: "LAX",
    to: "SFO",
    oneWayDate: "Dec 30",
    dateRange: "Dec 30 - jun 11",
    departure_time: "7:00AM",
    return_time: "4:15PM",
    stop_number: "1",
    stop_duration: "2h 45m",
    stop_place: "HNL",
    round_trip_price: "690",
    seat_class: "a",
    available_seats: 10,
    from_city: "California",
    from_country: "US",
    to_city: "Tokyo",
    to_country: "Japan",
    trip_seat: "economy",
  },
  {
    id: 5,
    img: "flight_image/Delta Airlines.svg",
    flight_number: "FIG4312",
    airline_name: "Hawaiian Airlines",
    duration: "16h 45m",
    from: "SFO",
    to: "LAX",
    oneWayDate: "Dec 30",
    dateRange: "Dec 26 - Dec 30",
    departure_time: "7:00AM",
    return_time: "4:15PM",
    stop_number: "1",
    stop_duration: "2h 45m",
    stop_place: "HNL",
    round_trip_price: "756",
    seat_class: "a",
    available_seats: 20,
    from_city: "Tokyo",
    from_country: "Japan",
    to_city: "California",
    to_country: "US",
    trip_seat: "business",
  },
  {
    id: 6,
    img: "flight_image/Hawaiian Airlines.svg",
    flight_number: "FIG4312",
    airline_name: "Delta Airlines",
    duration: "16h 45m",
    from: "SFO",
    to: "LAX",
    oneWayDate: "Dec 30",
    dateRange: "Dec 26 - Dec 30",
    departure_time: "7:00AM",
    return_time: "4:15PM",
    stop_number: "1",
    stop_duration: "2h 45m",
    stop_place: "HNL",
    round_trip_price: "756",
    // seat_class: "a",
    available_seats: 20,
    from_city: "Tokyo",
    from_country: "Japan",
    to_city: "California",
    to_country: "US",
    trip_seat: "business",
  },
];
