const seatsData = [
  {
    rowNumber: 1,
    type: "business",
    seats: [
      { id: "1A", isReserved: true },
      { id: "1B", isReserved: false },
      { id: "1C", isReserved: false },
      { id: "1D", isReserved: true },
    ],
  },
  {
    rowNumber: 2,
    type: "business",
    seats: [
      { id: "2A", isReserved: true },
      { id: "2B", isReserved: false },
      { id: "2C", isReserved: false },
      { id: "2D", isReserved: true },
    ],
  },
  {
    rowNumber: 3,
    type: "business",
    seats: [
      { id: "3A", isReserved: true },
      { id: "3B", isReserved: false },
      { id: "3C", isReserved: false },
      { id: "3D", isReserved: true },
    ],
  },
  {
    rowNumber: 4,
    type: "business",
    seats: [
      { id: "4A", isReserved: true },
      { id: "4B", isReserved: false },
      { id: "4C", isReserved: false },
      { id: "4D", isReserved: true },
    ],
  },
  {
    rowNumber: 5,
    type: "business",
    seats: [
      { id: "5A", isReserved: true },
      { id: "5B", isReserved: false },
      { id: "5C", isReserved: false },
      { id: "5D", isReserved: true },
    ],
  },
  {
    rowNumber: 6,
    type: "economy",
    seats: [
      { id: "6A", isReserved: false },
      { id: "6B", isReserved: true },
      { id: "6C", isReserved: false },
      { id: "6D", isReserved: true },
      { id: "6E", isReserved: false },
      { id: "6F", isReserved: true },
    ],
  },
  {
    rowNumber: 7,
    type: "economy",
    seats: [
      { id: "7A", isReserved: false },
      { id: "7B", isReserved: true },
      { id: "7C", isReserved: false },
      { id: "7D", isReserved: true },
      { id: "7E", isReserved: false },
      { id: "7F", isReserved: true },
    ],
  },
  {
    rowNumber: 8,
    type: "economy",
    seats: [
      { id: "8A", isReserved: false },
      { id: "8B", isReserved: true },
      { id: "8C", isReserved: true },
      { id: "8D", isReserved: false },
      { id: "8E", isReserved: false },
      { id: "8F", isReserved: true },
    ],
  },
  {
    rowNumber: 9,
    type: "economy",
    seats: [
      { id: "9A", isReserved: false },
      { id: "9B", isReserved: true },
      { id: "9C", isReserved: false },
      { id: "9D", isReserved: true },
      { id: "9E", isReserved: false },
      { id: "9F", isReserved: false },
    ],
  },
  {
    rowNumber: 10,
    type: "economy",
    seats: [
      { id: "10A", isReserved: true },
      { id: "10B", isReserved: true },
      { id: "10C", isReserved: false },
      { id: "10D", isReserved: true },
      { id: "10E", isReserved: false },
      { id: "10F", isReserved: true },
    ],
  },
  {
    rowNumber: 11,
    type: "economy",
    seats: [
      { id: "11A", isReserved: true },
      { id: "11B", isReserved: true },
      { id: "11C", isReserved: false },
      { id: "11D", isReserved: true },
      { id: "11E", isReserved: false },
      { id: "11F", isReserved: true },
    ],
  },
  {
    rowNumber: 12,
    type: "economy",
    seats: [
      { id: "12A", isReserved: true },
      { id: "12B", isReserved: false },
      { id: "12C", isReserved: false },
      { id: "12D", isReserved: true },
      { id: "12E", isReserved: false },
      { id: "12F", isReserved: true },
    ],
  },
  {
    rowNumber: 13,
    type: "economy",
    seats: [
      { id: "13A", isReserved: false },
      { id: "13B", isReserved: false },
      { id: "13C", isReserved: false },
      { id: "13D", isReserved: true },
      { id: "13E", isReserved: false },
      { id: "13F", isReserved: true },
    ],
  },
  {
    rowNumber: 14,
    type: "economy",
    seats: [
      { id: "14A", isReserved: true },
      { id: "14B", isReserved: false },
      { id: "14C", isReserved: false },
      { id: "14D", isReserved: true },
      { id: "14E", isReserved: false },
      { id: "14F", isReserved: true },
    ],
  },
  {
    rowNumber: 15,
    type: "economy",
    seats: [
      { id: "15A", isReserved: true },
      { id: "15B", isReserved: true },
      { id: "15C", isReserved: false },
      { id: "15D", isReserved: false },
      { id: "15E", isReserved: false },
      { id: "15F", isReserved: true },
    ],
  },
  {
    rowNumber: 16,
    type: "economy",
    seats: [
      { id: "16A", isReserved: true },
      { id: "16B", isReserved: true },
      { id: "16C", isReserved: false },
      { id: "16D", isReserved: true },
      { id: "16E", isReserved: false },
      { id: "16F", isReserved: true },
    ],
  },
  {
    rowNumber: 17,
    type: "economy",
    seats: [
      { id: "17A", isReserved: false },
      { id: "17B", isReserved: true },
      { id: "17C", isReserved: false },
      { id: "17D", isReserved: true },
      { id: "17E", isReserved: false },
      { id: "17F", isReserved: true },
    ],
  },
  {
    rowNumber: 18,
    type: "economy",
    seats: [
      { id: "18A", isReserved: false },
      { id: "18B", isReserved: true },
      { id: "18C", isReserved: false },
      { id: "18D", isReserved: true },
      { id: "18E", isReserved: false },
      { id: "18F", isReserved: false },
    ],
  },
  {
    rowNumber: 19,
    type: "economy",
    seats: [
      { id: "19A", isReserved: false },
      { id: "19B", isReserved: false },
      { id: "19C", isReserved: false },
      { id: "19D", isReserved: true },
      { id: "19E", isReserved: false },
      { id: "19F", isReserved: true },
    ],
  },
  {
    rowNumber: 20,
    type: "economy",
    seats: [
      { id: "20A", isReserved: false },
      { id: "20B", isReserved: true },
      { id: "20C", isReserved: false },
      { id: "20D", isReserved: false },
      { id: "20E", isReserved: false },
      { id: "20F", isReserved: true },
    ],
  },
  {
    rowNumber: 21,
    type: "economy",
    seats: [
      { id: "21A", isReserved: false },
      { id: "21B", isReserved: true },
      { id: "21C", isReserved: false },
      { id: "21D", isReserved: true },
      { id: "21E", isReserved: false },
      { id: "21F", isReserved: false },
    ],
  },
];

export default seatsData;
